Repository ToriArtis/2NY-Backend, pull requests merged in 2024-08, with the labels that each got.

#95 ✨Feat: buildspec, procfile upload
  Procfile
  buildspec.yml
Labels: 🧵Chore, ✨Feat, 🍸조민준🍸

#101 ✨ Feat : amin add
  src/main/java/com/mega/_NY/auth/entity/UserRoles.java
  src/main/java/com/mega/_NY/auth/service/UserService.java
Labels: ✨Feat, 🥕 채현영🥕

#103 ✨ Feat : refresh token add
  build/classes/java/main/com/mega/_NY/auth/config/SecurityConfig.class
  build/classes/java/main/com/mega/_NY/auth/config/WebMvcConfig.class
  build/classes/java/main/com/mega/_NY/auth/entity/AuthUtils.class
  build/classes/java/main/com/mega/_NY/auth/entity/UserRoles.class
  build/classes/java/main/com/mega/_NY/auth/jwt/JwtAuthenticationFilter.class
  build/classes/java/main/com/mega/_NY/auth/jwt/TokenProvider.class
  build/classes/java/main/com/mega/_NY/auth/repository/UserRepository.class
  build/classes/java/main/com/mega/_NY/auth/service/UserService.class
  build/generated/sources/annotationProcessor/java/main/com/mega/_NY/cart/mapper/CartMapperImpl.java
  build/generated/sources/annotationProcessor/java/main/com/mega/_NY/cart/mapper/ItemCartMapperImpl.java
  build/generated/sources/annotationProcessor/java/main/com/mega/_NY/item/mapper/ItemMapperImpl.java
  build/generated/sources/annotationProcessor/java/main/com/mega/_NY/orders/mapper/ItemOrdersMapperImpl.java
  build/generated/sources/annotationProcessor/java/main/com/mega/_NY/orders/mapper/OrdersMapperImpl.java
  build/generated/sources/annotationProcessor/java/main/com/mega/_NY/review/mapper/ReviewMapperImpl.java
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/mega/_NY/auth/config/SecurityConfig.java
  src/main/java/com/mega/_NY/auth/config/WebMvcConfig.java
  src/main/java/com/mega/_NY/auth/entity/AuthUtils.java
  src/main/java/com/mega/_NY/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/mega/_NY/auth/jwt/TokenProvider.java
  src/main/java/com/mega/_NY/auth/repository/UserRepository.java
  src/main/java/com/mega/_NY/auth/service/UserService.java
Labels: ✨Feat, 🥕 채현영🥕

#104 ✨Feat: 전체 유저 보여주기
  build/classes/java/main/com/mega/_NY/auth/config/WebMvcConfig.class
  build/classes/java/main/com/mega/_NY/auth/controller/UserController.class
  build/classes/java/main/com/mega/_NY/auth/service/UserService.class
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/mega/_NY/auth/config/WebMvcConfig.java
  src/main/java/com/mega/_NY/auth/controller/UserController.java
  src/main/java/com/mega/_NY/auth/service/UserService.java
Labels: 🐛Bug, ✨Feat, 🥕 채현영🥕

#105 ✨ Feat : setRole
  src/main/java/com/mega/_NY/auth/config/SecurityConfig.java
  src/main/java/com/mega/_NY/auth/controller/ChatGPTController.java
  src/main/java/com/mega/_NY/auth/controller/OauthUserController.java
  src/main/java/com/mega/_NY/auth/controller/TestContoller.java
  src/main/java/com/mega/_NY/auth/controller/UserController.java
  src/main/java/com/mega/_NY/auth/dto/UserDTO.java
  src/main/java/com/mega/_NY/auth/entity/User.java
  src/main/java/com/mega/_NY/auth/jwt/TokenProvider.java
  src/main/java/com/mega/_NY/auth/service/ChatGPTService.java
  src/main/java/com/mega/_NY/auth/service/CustomUserDetailsService.java
  src/main/java/com/mega/_NY/auth/service/OAuth2Service.java
  src/main/java/com/mega/_NY/auth/service/UserInfoFilter.java
  src/main/java/com/mega/_NY/auth/service/UserService.java
Labels: ✨Feat, 🥕 채현영🥕

#107 ✨ Feat : UserRoles remove
  build/classes/java/main/com/mega/_NY/auth/dto/UserDTO$FindDTO.class
  build/classes/java/main/com/mega/_NY/auth/dto/UserDTO$LoginDTO.class
  build/classes/java/main/com/mega/_NY/auth/dto/UserDTO$ResponseDTO$ResponseDTOBuilder.class
  build/classes/java/main/com/mega/_NY/auth/dto/UserDTO$ResponseDTO.class
  build/classes/java/main/com/mega/_NY/auth/entity/User.class
  build/classes/java/main/com/mega/_NY/auth/service/UserService.class
  build/generated/sources/annotationProcessor/java/main/com/mega/_NY/cart/mapper/CartMapperImpl.java
  build/generated/sources/annotationProcessor/java/main/com/mega/_NY/cart/mapper/ItemCartMapperImpl.java
  build/generated/sources/annotationProcessor/java/main/com/mega/_NY/item/mapper/ItemMapperImpl.java
  build/generated/sources/annotationProcessor/java/main/com/mega/_NY/orders/mapper/ItemOrdersMapperImpl.java
  build/generated/sources/annotationProcessor/java/main/com/mega/_NY/orders/mapper/OrdersMapperImpl.java
  build/generated/sources/annotationProcessor/java/main/com/mega/_NY/review/mapper/ReviewMapperImpl.java
  build/tmp/compileJava/previous-compilation-data.bin
  images/2.png
  images/5897718d-be3c-4167-8fdd-8eaa7cdc8162.gif
  src/main/java/com/mega/_NY/auth/config/DataInitializer.java
  src/main/java/com/mega/_NY/auth/dto/UserDTO.java
  src/main/java/com/mega/_NY/auth/entity/User.java
  src/main/java/com/mega/_NY/auth/service/UserService.java
Labels: ✨Feat, 🍸조민준🍸
