Repository ToriArtis/2NY-Backend, pull requests merged in 2024-07, with the labels that each got.

#38 ✨ Feat: 관리자 권한주기
  src/main/java/com/mega/_NY/auth/config/SecurityConfig.java
  src/main/java/com/mega/_NY/auth/config/exception/ExceptionCode.java
  src/main/java/com/mega/_NY/auth/controller/UserController.java
  src/main/java/com/mega/_NY/auth/dto/AuthSecurityDTO.java
  src/main/java/com/mega/_NY/auth/dto/UserDTO.java
  src/main/java/com/mega/_NY/auth/entity/User.java
  src/main/java/com/mega/_NY/auth/service/CustomUserDetailsService.java
  src/main/java/com/mega/_NY/auth/service/UserService.java
Labels: 🐛Bug, ✨Feat, 🥕 채현영🥕

#39 ✨Feat: Item crud Authentication
  src/main/java/com/mega/_NY/item/controller/ItemController.java
Labels: ✨Feat

#40 ✨Feat: Cart Authentication + Pagenation
  .idea/vcs.xml
  src/main/java/com/mega/_NY/cart/controller/CartController.java
  src/main/java/com/mega/_NY/cart/controller/ItemCartController.java
  src/main/java/com/mega/_NY/cart/repository/CartRepository.java
  src/main/java/com/mega/_NY/cart/service/CartService.java
  src/main/java/com/mega/_NY/orders/controller/OrdersController.java
  src/main/java/com/mega/_NY/orders/dto/ItemOrderDTO.java
  src/main/java/com/mega/_NY/orders/entity/ItemOrders.java
  src/main/java/com/mega/_NY/orders/mapper/ItemOrdersMapper.java
  src/main/java/com/mega/_NY/orders/mapper/OrdersMapper.java
  src/main/java/com/mega/_NY/orders/repository/OrdersRepository.java
  src/main/java/com/mega/_NY/orders/service/OrdersService.java
Labels: 🧵Chore, ✨Feat, 🦦 김신이🦦

#41 ✨Feat: Order Authentication
  src/main/java/com/mega/_NY/orders/controller/OrdersController.java
Labels: ✨Feat

#42 ✨Feat: Review Feat
  src/main/java/com/mega/_NY/review/controller/ReviewController.java
  src/main/java/com/mega/_NY/review/dto/ReviewDTO.java
  src/main/java/com/mega/_NY/review/entity/Review.java
  src/main/java/com/mega/_NY/review/mapper/ReviewMapper.java
  src/main/java/com/mega/_NY/review/repository/ReviewRepository.java
  src/main/java/com/mega/_NY/review/service/ReviewService.java
Labels: ✨Feat, 🔮 이소현🔮

#43 ✨Feat: oauth 기능 추가
  build.gradle
  src/main/java/com/mega/_NY/auth/config/SecurityConfig.java
  src/main/java/com/mega/_NY/auth/controller/OauthUserController.java
  src/main/java/com/mega/_NY/auth/controller/UserController.java
  src/main/java/com/mega/_NY/auth/entity/OAuthAttributes.java
  src/main/java/com/mega/_NY/auth/entity/User.java
  src/main/java/com/mega/_NY/auth/repository/UserRepository.java
  src/main/java/com/mega/_NY/auth/service/OAuth2Service.java
  src/main/java/com/mega/_NY/auth/service/UserService.java
  src/main/resources/index.html
Labels: ✨Feat, 🥕 채현영🥕

#45 ✨Feat: Orders + Review ADMIN Management
  .idea/vcs.xml
  src/main/java/com/mega/_NY/auth/config/exception/ExceptionCode.java
  src/main/java/com/mega/_NY/cart/controller/CartController.java
  src/main/java/com/mega/_NY/orders/controller/OrdersController.java
  src/main/java/com/mega/_NY/orders/service/OrdersService.java
  src/main/java/com/mega/_NY/review/service/ReviewService.java
Labels: 🧵Chore, ✨Feat, 🦦 김신이🦦

#46 ✨Feat: Admin Order List
  src/main/java/com/mega/_NY/cart/controller/CartController.java
  src/main/java/com/mega/_NY/orders/controller/OrdersController.java
  src/main/java/com/mega/_NY/orders/repository/OrdersRepository.java
  src/main/java/com/mega/_NY/orders/service/OrdersService.java
Labels: ✨Feat, 🦦 김신이🦦

#47 ✨Feat: Item pagenition, filtering, Testdb Create 🧵Chore: SecurityConfig permit add
  src/main/java/com/mega/_NY/auth/config/SecurityConfig.java
  src/main/java/com/mega/_NY/item/controller/ItemController.java
  src/main/java/com/mega/_NY/item/entity/TestDataInitializer.java
  src/main/java/com/mega/_NY/item/repository/ItemRepository.java
  src/main/java/com/mega/_NY/item/service/ItemService.java
Labels: 🐛Bug, 🧵Chore, ✨Feat, 🍸조민준🍸

#51 🐛 Fix : oauth out, controller url fix
  src/main/java/com/mega/_NY/auth/config/SecurityConfig.java
  src/main/java/com/mega/_NY/auth/controller/UserController.java
Labels: 🐛Bug, 🧵Chore, 👻help wanted, 🥕 채현영🥕

#52 ✨Feat: Pagenation Add
  src/main/java/com/mega/_NY/review/controller/ReviewController.java
  src/main/java/com/mega/_NY/review/repository/ReviewRepository.java
  src/main/java/com/mega/_NY/review/service/ReviewService.java
Labels: ✨Feat, 🔮 이소현🔮

#53 🐛Fix: Review ADMIN management fix + Cart Pagenation fix
  src/main/java/com/mega/_NY/cart/controller/CartController.java
  src/main/java/com/mega/_NY/cart/repository/CartRepository.java
  src/main/java/com/mega/_NY/cart/repository/ItemCartRepository.java
  src/main/java/com/mega/_NY/cart/service/CartService.java
  src/main/java/com/mega/_NY/orders/entity/ItemOrders.java
  src/main/java/com/mega/_NY/orders/repository/ItemOrdersRepository.java
  src/main/java/com/mega/_NY/orders/service/ItemOrdersService.java
  src/main/java/com/mega/_NY/orders/service/OrdersService.java
  src/main/java/com/mega/_NY/review/service/ReviewService.java
Labels: 🐛Bug, 🦦 김신이🦦

#54 🐛Fix: ItemOrdersMapper Fix
  src/main/java/com/mega/_NY/orders/mapper/ItemOrdersMapper.java
Labels: 🐛Bug, 🦦 김신이🦦

#56 🐛Fix: ItemOrders Remove Date
  src/main/java/com/mega/_NY/orders/dto/ItemOrderDTO.java
  src/main/java/com/mega/_NY/orders/mapper/ItemOrdersMapper.java
Labels: 🐛Bug, 🦦 김신이🦦

#57 🧵Chore: Quantity Min Setting, Review Typo Fix
  src/main/java/com/mega/_NY/cart/dto/ItemCartDTO.java
  src/main/java/com/mega/_NY/orders/dto/ItemOrderDTO.java
  src/main/java/com/mega/_NY/review/controller/ReviewController.java
Labels: 🧵Chore, 🔮 이소현🔮, 🦦 김신이🦦

#58 ✨ Feat: cors settings add
  src/main/java/com/mega/_NY/auth/config/SecurityConfig.java
Labels: ✨Feat, 🥕 채현영🥕

#59 ✨ DetailItem Modify
  src/main/java/com/mega/_NY/item/controller/ItemController.java
  src/main/java/com/mega/_NY/item/dto/ItemWithReviewsDTO.java
  src/main/java/com/mega/_NY/item/service/ItemService.java
Labels: ✨Feat, 🔮 이소현🔮

#60 🐛 Fix itemDTO, ItemConroller, ItemService
  build.gradle
  src/main/java/com/mega/_NY/item/controller/ItemController.java
  src/main/java/com/mega/_NY/item/dto/ItemTest.java
  src/main/java/com/mega/_NY/item/service/ItemService.java
Labels: 🐛Bug, ♻️Refactor, ✨Feat, 🍸조민준🍸

#61 🐛Fix: Cart Price Code Fix
  src/main/java/com/mega/_NY/cart/dto/ItemCartDTO.java
  src/main/java/com/mega/_NY/cart/mapper/ItemCartMapper.java
  src/main/java/com/mega/_NY/cart/service/ItemCartService.java
Labels: 🐛Bug, 🦦 김신이🦦

#62 🧵Chore: ItemCartDTO In ItemTitle
  src/main/java/com/mega/_NY/cart/dto/ItemCartDTO.java
  src/main/java/com/mega/_NY/cart/mapper/ItemCartMapper.java
Labels: 🧵Chore, 🦦 김신이🦦

#63 🧵Chore: ItemOrdersDTO in ItemSize + Color
  src/main/java/com/mega/_NY/orders/dto/ItemOrderDTO.java
  src/main/java/com/mega/_NY/orders/mapper/ItemOrdersMapper.java
Labels: 🧵Chore, 🦦 김신이🦦

#65 🧵Chore: Orders User RealName Mapper
  src/main/java/com/mega/_NY/orders/mapper/OrdersMapper.java
Labels: 🧵Chore, 🦦 김신이🦦

#66 ✨Feat: Item crud fin
  src/main/java/com/mega/_NY/item/controller/ItemController.java
  src/main/java/com/mega/_NY/item/dto/ItemTest.java
  src/main/java/com/mega/_NY/item/entity/TestDataInitializer.java
  src/main/java/com/mega/_NY/item/service/ItemService.java
Labels: 🧵Chore, ✨Feat, 🍸조민준🍸

#67 ✨ Feat: chat gpt add
  src/main/java/com/mega/_NY/auth/config/ChatGPTConfig.java
  src/main/java/com/mega/_NY/auth/config/SecurityConfig.java
  src/main/java/com/mega/_NY/auth/controller/ChatGPTController.java
  src/main/java/com/mega/_NY/auth/dto/ChatGPTDTO.java
  src/main/java/com/mega/_NY/auth/service/ChatGPTService.java
Labels: ✨Feat, 🥕 채현영🥕

#68 🐛Fix: Itemtest image
  src/main/java/com/mega/_NY/item/dto/ItemTest.java
Labels: 🐛Bug, ♻️Refactor, 🍸조민준🍸

#69 ✨Feat: Cart Clear Controller
  src/main/java/com/mega/_NY/cart/controller/CartController.java
  src/main/java/com/mega/_NY/cart/service/ItemCartService.java
Labels: ✨Feat, 🦦 김신이🦦

#70 🐛Fix: UploadFile Fix
  src/main/java/com/mega/_NY/item/service/ItemService.java
  src/main/resources/static/images/1720425322681_cat.jpg
  src/main/resources/static/images/1720425322683_bg.png
  src/main/resources/static/images/1720425555150_cat.jpg
Labels: 🐛Bug

#71 🐛Fix: ItemModify Add
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
  src/main/java/com/mega/_NY/item/controller/ItemController.java
  src/main/java/com/mega/_NY/item/service/ItemService.java
  src/main/resources/static/images/1720427480314_카카오.png
  src/main/resources/static/images/1720427480316_Figma.png
  src/main/resources/static/images/1720427480317_Jira.png
  src/main/resources/static/images/1720429337189_Figma.png
  src/main/resources/static/images/1720429337191_네이버 (2).png
  src/main/resources/static/images/1720435873141_Jira.png
  src/main/resources/static/images/1720435873144_카카오 1.png
  src/main/resources/static/images/1720436169114_메인.png
  src/main/resources/static/images/1720436169115_Jira.png
Labels: 🐛Bug, 🔮 이소현🔮

#72 🐛Fix: OrderStatus Code Fix
  src/main/java/com/mega/_NY/orders/controller/OrdersController.java
  src/main/java/com/mega/_NY/orders/dto/ItemOrderDTO.java
  src/main/java/com/mega/_NY/orders/dto/OrdersDTO.java
  src/main/java/com/mega/_NY/orders/entity/OrderStatus.java
  src/main/java/com/mega/_NY/orders/mapper/ItemOrdersMapper.java
  src/main/java/com/mega/_NY/orders/service/OrdersService.java
  src/main/resources/static/images/1720442406528_sdsd.jpg
  src/main/resources/static/images/1720442406531_sdsd.jpg
Labels: 🐛Bug, 🧵Chore, 🦦 김신이🦦

#73 🧵Chore: Review limit
  src/main/java/com/mega/_NY/auth/config/exception/ExceptionCode.java
  src/main/java/com/mega/_NY/review/repository/ReviewRepository.java
  src/main/java/com/mega/_NY/review/service/ReviewService.java
  src/main/resources/static/images/1720425322681_cat.jpg
  src/main/resources/static/images/1720425322683_bg.png
  src/main/resources/static/images/1720425555150_cat.jpg
  src/main/resources/static/images/1720427480314_카카오.png
  src/main/resources/static/images/1720427480316_Figma.png
  src/main/resources/static/images/1720427480317_Jira.png
  src/main/resources/static/images/1720429337189_Figma.png
  src/main/resources/static/images/1720429337191_네이버 (2).png
  src/main/resources/static/images/1720435873141_Jira.png
  src/main/resources/static/images/1720435873144_카카오 1.png
  src/main/resources/static/images/1720436169114_메인.png
  src/main/resources/static/images/1720436169115_Jira.png
  src/main/resources/static/images/1720442406528_sdsd.jpg
  src/main/resources/static/images/1720442406531_sdsd.jpg
Labels: 🧵Chore, 🔮 이소현🔮

#74 ✨ Feat: password feat
  src/main/java/com/mega/_NY/auth/controller/UserController.java
  src/main/java/com/mega/_NY/auth/repository/UserRepository.java
  src/main/java/com/mega/_NY/auth/service/UserInfoFilter.java
  src/main/java/com/mega/_NY/auth/service/UserService.java
Labels: ✨Feat, 🥕 채현영🥕

#75 🧵Chore: OrdersDTO In Email
  src/main/java/com/mega/_NY/orders/dto/OrdersDTO.java
  src/main/java/com/mega/_NY/orders/mapper/OrdersMapper.java
  src/main/resources/static/images/1720487085554_cat.jpg
  src/main/resources/static/images/1720487085557_IMG_9446.jpg
Labels: 🧵Chore, 🦦 김신이🦦

#76 ✨ Feat: 아이디 찾기
  src/main/java/com/mega/_NY/auth/controller/UserController.java
  src/main/java/com/mega/_NY/auth/dto/UserDTO.java
  src/main/java/com/mega/_NY/auth/repository/UserRepository.java
  src/main/java/com/mega/_NY/auth/service/UserService.java
Labels: ✨Feat, 🥕 채현영🥕

#77 🐛Fix: Search Controller + Security modify
  src/main/java/com/mega/_NY/auth/config/SecurityConfig.java
  src/main/java/com/mega/_NY/item/controller/ItemController.java
  src/main/resources/static/images/1720504232048_구글.png
  src/main/resources/static/images/1720504232052_카카오.png
  src/main/resources/static/images/1720515621516_카카오.png
  src/main/resources/static/images/1720515621520_메인.png
Labels: 🐛Bug, 🔮 이소현🔮

#78 ✨Feat: Search Again
  src/main/java/com/mega/_NY/item/controller/ItemController.java
  src/main/java/com/mega/_NY/item/repository/ItemRepository.java
  src/main/java/com/mega/_NY/item/repository/SearchRepository.java
  src/main/java/com/mega/_NY/item/service/ItemService.java
  src/main/resources/static/images/1720487085554_cat.jpg
  src/main/resources/static/images/1720487085557_IMG_9446.jpg
  src/main/resources/static/images/1720504232048_구글.png
  src/main/resources/static/images/1720504232052_카카오.png
  src/main/resources/static/images/1720515621516_카카오.png
  src/main/resources/static/images/1720515621520_메인.png
Labels: ✨Feat, 🔮 이소현🔮

#79 🐛Fix: Order Item Sales Update Fix
  src/main/java/com/mega/_NY/auth/config/exception/ExceptionCode.java
  src/main/java/com/mega/_NY/orders/service/ItemOrdersService.java
  src/main/java/com/mega/_NY/orders/service/OrdersService.java
Labels: 🐛Bug, 🦦 김신이🦦

#80 🐛 Fix: ItemOrder BuyNow Change Service Code Fix
  src/main/java/com/mega/_NY/orders/service/ItemOrdersService.java
  src/main/java/com/mega/_NY/orders/service/OrdersService.java
Labels: 🐛Bug, 🦦 김신이🦦

#81 🐛 Fix : categoty enum, testdb initializer
  src/main/java/com/mega/_NY/item/entity/ItemCategory.java
  src/main/java/com/mega/_NY/item/entity/TestDataInitializer.java
  src/main/resources/static/images/1720426222065_.png
  src/main/resources/static/images/1720426222067_bannder.png
  src/main/resources/static/images/1720431505391_.png
  src/main/resources/static/images/1720431505393_blur.png
  src/main/resources/static/images/1720572698618_2.png
  src/main/resources/static/images/1720572698620_1.png
  src/main/resources/static/images/1720573076863_1.png
  src/main/resources/static/images/1720573076864_q.png
  src/main/resources/static/images/1720573273957_q.png
  src/main/resources/static/images/1720573273959_bannder.png
  src/main/resources/static/images/1720573365573_blur.png
  src/main/resources/static/images/1720573365575_.png
  src/main/resources/static/images/1720574233583_.png
  src/main/resources/static/images/1720574233585_q.png
  src/main/resources/static/images/1720574628828_.png
  src/main/resources/static/images/1720574628830_bannder.png
  src/main/resources/static/images/1720575116703_.png
  src/main/resources/static/images/1720575116707_bannder.png
  src/main/resources/static/images/1720575162213_blur.png
  src/main/resources/static/images/1720575162214_1.png
  src/main/resources/static/images/1720575241063_bg.png
  src/main/resources/static/images/1720575241065_.png
  src/main/resources/static/images/1720581259580_.png
  src/main/resources/static/images/1720581259584_blur.png
  src/main/resources/static/images/1720581259585_1.png
  src/main/resources/static/images/1720581259586_2.png
  src/main/resources/static/images/1720597360639_1 (2).png
  src/main/resources/static/images/1720597360642_화면 캡처 2024-07-10 162008.png
  src/main/resources/static/images/1720601948692_1 (2).png
  src/main/resources/static/images/1720601948694_1 (2).png
Labels: 🐛Bug, 🍸조민준🍸

#82 🐛Fix: Review orderId Fix
  src/main/java/com/mega/_NY/review/dto/ReviewDTO.java
  src/main/java/com/mega/_NY/review/entity/Review.java
  src/main/java/com/mega/_NY/review/repository/ReviewRepository.java
  src/main/java/com/mega/_NY/review/service/ReviewService.java
Labels: 🐛Bug, 🔮 이소현🔮

#83 ✨Feat: OAuth2 Sosiacl Login finished Google,KaKao
  hs_err_pid23732.log
  hs_err_pid3480.log
  replay_pid23732.log
  replay_pid3480.log
  src/main/java/com/mega/_NY/auth/config/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/mega/_NY/auth/config/SecurityConfig.java
  src/main/java/com/mega/_NY/auth/controller/OauthUserController.java
  src/main/java/com/mega/_NY/auth/entity/OAuthAttributes.java
  src/main/java/com/mega/_NY/auth/entity/User.java
  src/main/java/com/mega/_NY/auth/service/OAuth2Service.java
  src/main/java/com/mega/_NY/item/entity/TestDataInitializer.java
  src/main/resources/static/images/default_Thumbnail.png
  src/main/resources/static/images/default_descriptionImage.png
Labels: 🐛Bug, ✨Feat, 🍸조민준🍸

#84 🐛Fix: Naver login fix
  hs_err_pid23616.log
  replay_pid23616.log
  src/main/java/com/mega/_NY/auth/entity/OAuthAttributes.java
  src/main/java/com/mega/_NY/auth/service/OAuth2Service.java
Labels: 🐛Bug

#85 ✨Feat: Sosial login feat passwordEncorder
  src/main/java/com/mega/_NY/auth/config/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/mega/_NY/auth/config/SecurityConfig.java
  src/main/java/com/mega/_NY/auth/entity/OAuthAttributes.java
  src/main/java/com/mega/_NY/auth/service/OAuth2Service.java
Labels: ✨Feat

#86 🐛Fix: Filter Fix
  src/main/java/com/mega/_NY/item/controller/ItemController.java
  src/main/java/com/mega/_NY/item/repository/ItemRepository.java
  src/main/java/com/mega/_NY/item/service/ItemService.java
  src/main/resources/static/images/1720754352794_메인.png
  src/main/resources/static/images/1720754352797_구글.png
Labels: 🐛Bug, 🔮 이소현🔮

#87 🧵Chore: Review Pagination Sort
  src/main/java/com/mega/_NY/item/controller/ItemController.java
  src/main/java/com/mega/_NY/review/controller/ReviewController.java
  src/main/resources/static/images/1720426222067_bannder.png
  src/main/resources/static/images/1720431505391_.png
  src/main/resources/static/images/1720431505393_blur.png
  src/main/resources/static/images/1720572698620_1.png
  src/main/resources/static/images/1720573076863_1.png
  src/main/resources/static/images/1720573076864_q.png
  src/main/resources/static/images/1720573273957_q.png
  src/main/resources/static/images/1720573273959_bannder.png
  src/main/resources/static/images/1720573365573_blur.png
  src/main/resources/static/images/1720573365575_.png
  src/main/resources/static/images/1720574233583_.png
  src/main/resources/static/images/1720574233585_q.png
  src/main/resources/static/images/1720574628828_.png
  src/main/resources/static/images/1720574628830_bannder.png
  src/main/resources/static/images/1720575116703_.png
  src/main/resources/static/images/1720575116707_bannder.png
  src/main/resources/static/images/1720575162213_blur.png
  src/main/resources/static/images/1720575162214_1.png
  src/main/resources/static/images/1720575241063_bg.png
  src/main/resources/static/images/1720575241065_.png
  src/main/resources/static/images/1720581259580_.png
  src/main/resources/static/images/1720581259584_blur.png
  src/main/resources/static/images/1720581259585_1.png
  src/main/resources/static/images/1720581259586_2.png
  src/main/resources/static/images/1720597360639_1 (2).png
  src/main/resources/static/images/1720597360642_화면 캡처 2024-07-10 162008.png
  src/main/resources/static/images/1720601948692_1 (2).png
  src/main/resources/static/images/1720601948694_1 (2).png
  src/main/resources/static/images/1720754352794_메인.png
  src/main/resources/static/images/1720754352797_구글.png
Labels: 🧵Chore, 🔮 이소현🔮

#88 🐛Fix: Item edit image fix
  hs_err_pid23616.log
  hs_err_pid23732.log
  hs_err_pid3480.log
  replay_pid23616.log
  replay_pid23732.log
  replay_pid3480.log
  src/main/java/com/mega/_NY/item/controller/ItemController.java
  src/main/java/com/mega/_NY/item/service/ItemService.java
Labels: 🐛Bug, 🍸조민준🍸

#89 ✨Feat: refresh token
  src/main/java/com/mega/_NY/auth/config/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/mega/_NY/auth/config/SecurityConfig.java
  src/main/java/com/mega/_NY/auth/controller/OauthUserController.java
  src/main/java/com/mega/_NY/auth/controller/UserController.java
  src/main/java/com/mega/_NY/auth/dto/UserDTO.java
  src/main/java/com/mega/_NY/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/mega/_NY/auth/jwt/TokenProvider.java
  src/main/java/com/mega/_NY/auth/service/Oauth2UserService.java
  src/main/java/com/mega/_NY/auth/service/UserService.java
Labels: 🐛Bug, ✨Feat, 🥕 채현영🥕

#90 ✨Feat: Error Page Setting
  src/main/java/com/mega/_NY/error/CustomErrorController.java
  src/main/java/com/mega/_NY/error/CustomException.java
Labels: ✨Feat, 🦦 김신이🦦

#91 ✨Feat: OAuth Cart Create
  src/main/java/com/mega/_NY/auth/service/OAuth2Service.java
  src/main/resources/static/images/1721184361502_white_skirt2.jpg
Labels: ✨Feat, 🦦 김신이🦦
