Repository ToriArtis/2NY-Backend, pull requests merged in 2024-06, with the labels that each got.

#7 ✨Feat: auth CRUD
  build.gradle
  src/main/java/com/mega/_NY/auth/config/PasswordEncoderConfig.java
  src/main/java/com/mega/_NY/auth/config/UserMapperConfig.java
  src/main/java/com/mega/_NY/auth/config/exception/BusinessLogicException.java
  src/main/java/com/mega/_NY/auth/config/exception/ExceptionCode.java
  src/main/java/com/mega/_NY/auth/controller/UserController.java
  src/main/java/com/mega/_NY/auth/dto/UserDTO.java
  src/main/java/com/mega/_NY/auth/entity/AuthUtils.java
  src/main/java/com/mega/_NY/auth/entity/User.java
  src/main/java/com/mega/_NY/auth/entity/UserRoles.java
  src/main/java/com/mega/_NY/auth/entity/UserStatus.java
  src/main/java/com/mega/_NY/auth/repository/UserRepository.java
  src/main/java/com/mega/_NY/auth/service/UserInfoFilter.java
  src/main/java/com/mega/_NY/auth/service/UserService.java
  src/main/java/com/mega/_NY/config/RootConfig.java
  src/main/resources/application.properties
Labels: ✨Feat, 🥕 채현영🥕

#8 🧵 Chorce: git commit check
  build.gradle
  src/main/java/com/mega/_NY/auth/config/CustomSecurityConfig.java
  src/main/java/com/mega/_NY/auth/config/RedisConfig.java
  src/main/java/com/mega/_NY/auth/config/details/PrincipalDetails.java
  src/main/java/com/mega/_NY/auth/config/details/PrincipalDetailsService.java
  src/main/java/com/mega/_NY/auth/config/handler/UserAccessDeniedHandler.java
  src/main/java/com/mega/_NY/auth/config/handler/UserAuthFailureHandler.java
  src/main/java/com/mega/_NY/auth/config/handler/UserAuthSuccessHandler.java
  src/main/java/com/mega/_NY/auth/config/handler/UserAuthenticationEntryPoint.java
  src/main/java/com/mega/_NY/auth/config/logout/Logout.java
  src/main/java/com/mega/_NY/auth/controller/UserController.java
  src/main/java/com/mega/_NY/auth/dto/LoginDTO.java
  src/main/java/com/mega/_NY/auth/jwt/JwtToken.java
  src/main/java/com/mega/_NY/auth/jwt/SecretKey.java
  src/main/java/com/mega/_NY/auth/jwt/filter/JWTLoginFilter.java
  src/main/java/com/mega/_NY/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/mega/_NY/auth/jwt/filter/JwtVerificationFilter.java
  src/main/java/com/mega/_NY/auth/repository/UserRepository.java
  src/main/resources/application.properties
Labels: 🧵Chore, 🥕 채현영🥕

#9 ✨Feat: Item structure setting
  src/main/java/com/mega/_NY/item/controller/ItemController.java
  src/main/java/com/mega/_NY/item/dto/ItemDTO.java
  src/main/java/com/mega/_NY/item/entity/Item.java
  src/main/java/com/mega/_NY/item/mapper/itemMapper.java
  src/main/java/com/mega/_NY/item/repository/ItemRepository.java
  src/main/java/com/mega/_NY/item/service/ItemService.java
Labels: ✨Feat

#10 ✨Feat: Auth 기능 추가
  build.gradle
  src/main/java/com/mega/_NY/auth/config/CustomFilterConfigurer.java
  src/main/java/com/mega/_NY/auth/config/CustomSecurityConfig.java
  src/main/java/com/mega/_NY/auth/config/RedisConfig.java
  src/main/java/com/mega/_NY/auth/config/UserMapperConfig.java
  src/main/java/com/mega/_NY/auth/config/details/PrincipalDetails.java
  src/main/java/com/mega/_NY/auth/config/details/PrincipalDetailsService.java
  src/main/java/com/mega/_NY/auth/config/handler/UserAuthSuccessHandler.java
  src/main/java/com/mega/_NY/auth/config/handler/UserAuthenticationEntryPoint.java
  src/main/java/com/mega/_NY/auth/config/logout/Logout.java
  src/main/java/com/mega/_NY/auth/controller/UserController.java
  src/main/java/com/mega/_NY/auth/dto/UserSignUpDTO.java
  src/main/java/com/mega/_NY/auth/entity/User.java
  src/main/java/com/mega/_NY/auth/jwt/filter/JWTLoginFilter.java
  src/main/java/com/mega/_NY/auth/jwt/filter/JwtVerificationFilter.java
  src/main/java/com/mega/_NY/auth/repository/UserRepository.java
  src/main/java/com/mega/_NY/auth/service/UserService.java
  src/main/resources/application.properties
  src/test/java/com/mega/_NY/repository/AuthRepositoryTests.java
  src/test/java/com/mega/_NY/service/AuthServiceTests.java
Labels: 🐛Bug, 🧵Chore, ✨Feat, 📌Test, 👻Etc, 🥕 채현영🥕

#12 📝Docs: spplication 문서 수정
  src/main/resources/application.properties
Labels: 📝Docs, 🥕 채현영🥕

#13 📝Docs: application.properties gitignore
  src/main/resources/application.properties
Labels: 📝Docs, 👻Etc, 🥕 채현영🥕

#14 ✨Feat: Cart Structure Setting
  src/main/java/com/mega/_NY/cart/controller/CartController.java
  src/main/java/com/mega/_NY/cart/controller/ItemCartController.java
  src/main/java/com/mega/_NY/cart/dto/CartDTO.java
  src/main/java/com/mega/_NY/cart/dto/ItemCartDTO.java
  src/main/java/com/mega/_NY/cart/entity/Cart.java
  src/main/java/com/mega/_NY/cart/entity/ItemCart.java
  src/main/java/com/mega/_NY/cart/repository/CartRepository.java
  src/main/java/com/mega/_NY/cart/repository/ItemCartRepository.java
  src/main/java/com/mega/_NY/cart/service/CartService.java
  src/main/java/com/mega/_NY/cart/service/ItemCartService.java
Labels: ✨Feat, 🦦 김신이🦦

#17 ✨ Feat: Order Structure Setting
  src/main/java/com/mega/_NY/order/controller/ItemOrderController.java
  src/main/java/com/mega/_NY/order/controller/OrderController.java
  src/main/java/com/mega/_NY/order/dto/ItemOrderDTO.java
  src/main/java/com/mega/_NY/order/dto/OrderDTO.java
  src/main/java/com/mega/_NY/order/entity/ItemOrder.java
  src/main/java/com/mega/_NY/order/entity/Order.java
  src/main/java/com/mega/_NY/order/entity/OrderStatus.java
  src/main/java/com/mega/_NY/order/repository/ItemOrderRepository.java
  src/main/java/com/mega/_NY/order/repository/OrderRepository.java
  src/main/java/com/mega/_NY/order/service/ItemOrderService.java
  src/main/java/com/mega/_NY/order/service/OrderService.java
Labels: ✨Feat, 🦦 김신이🦦

#18 ✨ Feat: User crud finish
  src/main/java/com/mega/_NY/auth/config/CustomFilterConfigurer.java
  src/main/java/com/mega/_NY/auth/config/CustomSecurityConfig.java
  src/main/java/com/mega/_NY/auth/config/details/PrincipalDetails.java
  src/main/java/com/mega/_NY/auth/config/details/PrincipalDetailsService.java
  src/main/java/com/mega/_NY/auth/config/handler/UserAuthSuccessHandler.java
  src/main/java/com/mega/_NY/auth/controller/UserController.java
  src/main/java/com/mega/_NY/auth/dto/LoginDTO.java
  src/main/java/com/mega/_NY/auth/dto/UserDTO.java
  src/main/java/com/mega/_NY/auth/dto/UserSignUpDTO.java
  src/main/java/com/mega/_NY/auth/entity/User.java
  src/main/java/com/mega/_NY/auth/jwt/filter/JWTLoginFilter.java
  src/main/java/com/mega/_NY/auth/jwt/filter/JwtVerificationFilter.java
  src/main/java/com/mega/_NY/auth/service/Oauth2UserService.java
  src/main/java/com/mega/_NY/auth/service/UserService.java
  src/test/java/com/mega/_NY/login/jwt/JwtTokenTest.java
  src/test/java/com/mega/_NY/service/AuthServiceTests.java
Labels: 🐛Bug, 👻help wanted, ✨Feat, 📌Test, 👻Etc, 🥕 채현영🥕

#19 ✨Feat: Cart + ItemCart Draft
  src/main/java/com/mega/_NY/auth/controller/UserController.java
  src/main/java/com/mega/_NY/auth/entity/User.java
  src/main/java/com/mega/_NY/auth/jwt/filter/JWTLoginFilter.java
  src/main/java/com/mega/_NY/cart/controller/CartController.java
  src/main/java/com/mega/_NY/cart/controller/ItemCartController.java
  src/main/java/com/mega/_NY/cart/dto/CartDTO.java
  src/main/java/com/mega/_NY/cart/dto/ItemCartDTO.java
  src/main/java/com/mega/_NY/cart/entity/Cart.java
  src/main/java/com/mega/_NY/cart/entity/ItemCart.java
  src/main/java/com/mega/_NY/cart/mapper/CartMapper.java
  src/main/java/com/mega/_NY/cart/mapper/ItemCartMapper.java
  src/main/java/com/mega/_NY/cart/repository/CartRepository.java
  src/main/java/com/mega/_NY/cart/repository/ItemCartRepository.java
  src/main/java/com/mega/_NY/cart/service/CartService.java
  src/main/java/com/mega/_NY/cart/service/ItemCartService.java
  src/main/java/com/mega/_NY/order/controller/ItemOrderController.java
  src/main/java/com/mega/_NY/order/controller/OrderController.java
  src/main/java/com/mega/_NY/order/dto/ItemOrderDTO.java
  src/main/java/com/mega/_NY/order/dto/OrderDTO.java
  src/main/java/com/mega/_NY/order/repository/ItemOrderRepository.java
  src/main/java/com/mega/_NY/order/repository/OrderRepository.java
  src/main/java/com/mega/_NY/order/service/ItemOrderService.java
  src/main/java/com/mega/_NY/order/service/OrderService.java
  src/main/java/com/mega/_NY/orders/controller/ItemOrdersController.java
  src/main/java/com/mega/_NY/orders/controller/OrdersController.java
  src/main/java/com/mega/_NY/orders/dto/ItemOrderDTO.java
  src/main/java/com/mega/_NY/orders/dto/OrdersDTO.java
  src/main/java/com/mega/_NY/orders/entity/ItemOrders.java
  src/main/java/com/mega/_NY/orders/entity/OrderStatus.java
  src/main/java/com/mega/_NY/orders/entity/Orders.java
  src/main/java/com/mega/_NY/orders/repository/ItemOrdersRepository.java
  src/main/java/com/mega/_NY/orders/repository/OrdersRepository.java
  src/main/java/com/mega/_NY/orders/service/ItemOrdersService.java
  src/main/java/com/mega/_NY/orders/service/OrdersService.java
  src/test/java/com/mega/_NY/repository/CartRepositoryTests.java
  src/test/java/com/mega/_NY/service/CartServiceTests.java
Labels: ✨Feat, 🦦 김신이🦦

#20 ✨Feat: item crud (cannot test)
  src/main/java/com/mega/_NY/auth/config/CustomFilterConfigurer.java
  src/main/java/com/mega/_NY/auth/config/CustomSecurityConfig.java
  src/main/java/com/mega/_NY/auth/jwt/SecretKey.java
  src/main/java/com/mega/_NY/item/controller/ItemController.java
  src/main/java/com/mega/_NY/item/dto/ItemDTO.java
  src/main/java/com/mega/_NY/item/mapper/ItemMapper.java
  src/main/java/com/mega/_NY/item/mapper/itemMapper.java
  src/main/java/com/mega/_NY/item/repository/ItemRepository.java
  src/main/java/com/mega/_NY/item/service/ItemService.java
  src/test/java/com/mega/_NY/controller/ItemControllerTest.java
  src/test/java/com/mega/_NY/login/jwt/JwtTokenTest.java
  src/test/java/com/mega/_NY/repository/AuthRepositoryTests.java
Labels: ✨Feat, 🍸조민준🍸

#21 ✨Feat: Order CRUD + Cart CRUD + Test (in progress..)
  src/main/java/com/mega/_NY/cart/controller/CartController.java
  src/main/java/com/mega/_NY/cart/controller/ItemCartController.java
  src/main/java/com/mega/_NY/cart/dto/CartDTO.java
  src/main/java/com/mega/_NY/cart/dto/ItemCartDTO.java
  src/main/java/com/mega/_NY/cart/entity/Cart.java
  src/main/java/com/mega/_NY/cart/entity/ItemCart.java
  src/main/java/com/mega/_NY/cart/mapper/CartMapper.java
  src/main/java/com/mega/_NY/cart/mapper/ItemCartMapper.java
  src/main/java/com/mega/_NY/cart/repository/ItemCartRepository.java
  src/main/java/com/mega/_NY/cart/service/CartService.java
  src/main/java/com/mega/_NY/cart/service/ItemCartService.java
  src/main/java/com/mega/_NY/cart/util/EntityUtils.java
  src/main/java/com/mega/_NY/orders/controller/ItemOrdersController.java
  src/main/java/com/mega/_NY/orders/controller/OrdersController.java
  src/main/java/com/mega/_NY/orders/dto/ItemOrderDTO.java
  src/main/java/com/mega/_NY/orders/dto/OrdersDTO.java
  src/main/java/com/mega/_NY/orders/entity/ItemOrders.java
  src/main/java/com/mega/_NY/orders/entity/OrderStatus.java
  src/main/java/com/mega/_NY/orders/entity/Orders.java
  src/main/java/com/mega/_NY/orders/mapper/ItemOrdersMapper.java
  src/main/java/com/mega/_NY/orders/mapper/OrdersMapper.java
  src/main/java/com/mega/_NY/orders/repository/ItemOrdersRepository.java
  src/main/java/com/mega/_NY/orders/repository/OrdersRepository.java
  src/main/java/com/mega/_NY/orders/service/ItemOrdersService.java
  src/main/java/com/mega/_NY/orders/service/OrdersService.java
  src/test/java/com/mega/_NY/controller/CartControllerTests.java
  src/test/java/com/mega/_NY/controller/ItemCartControllerTests.java
  src/test/java/com/mega/_NY/repository/CartRepositoryTests.java
  src/test/java/com/mega/_NY/repository/OrderRepositoryTests.java
  src/test/java/com/mega/_NY/service/CartServiceTests.java
  src/test/java/com/mega/_NY/service/ItemCartServiceTests.java
Labels: ✨Feat, 📌Test, 🦦 김신이🦦

#22 ✨ Feat : JWT add
  build.gradle
  src/main/java/com/mega/_NY/auth/config/CustomFilterConfigurer.java
  src/main/java/com/mega/_NY/auth/config/CustomSecurityConfig.java
  src/main/java/com/mega/_NY/auth/config/SecurityConfig.java
  src/main/java/com/mega/_NY/auth/config/WebMvcConfig.java
  src/main/java/com/mega/_NY/auth/config/details/PrincipalDetails.java
  src/main/java/com/mega/_NY/auth/config/details/PrincipalDetailsService.java
  src/main/java/com/mega/_NY/auth/config/exception/BusinessLogicException.java
  src/main/java/com/mega/_NY/auth/config/exception/ExceptionCode.java
  src/main/java/com/mega/_NY/auth/config/handler/UserAccessDeniedHandler.java
  src/main/java/com/mega/_NY/auth/config/handler/UserAuthFailureHandler.java
  src/main/java/com/mega/_NY/auth/config/handler/UserAuthSuccessHandler.java
  src/main/java/com/mega/_NY/auth/config/handler/UserAuthenticationEntryPoint.java
  src/main/java/com/mega/_NY/auth/config/logout/Logout.java
  src/main/java/com/mega/_NY/auth/controller/UserController.java
  src/main/java/com/mega/_NY/auth/dto/LoginDTO.java
  src/main/java/com/mega/_NY/auth/dto/ResponseDTO.java
  src/main/java/com/mega/_NY/auth/dto/UserDTO.java
  src/main/java/com/mega/_NY/auth/entity/User.java
  src/main/java/com/mega/_NY/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/mega/_NY/auth/jwt/JwtToken.java
  src/main/java/com/mega/_NY/auth/jwt/SecretKey.java
  src/main/java/com/mega/_NY/auth/jwt/TokenProvider.java
  src/main/java/com/mega/_NY/auth/jwt/filter/JWTLoginFilter.java
  src/main/java/com/mega/_NY/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/mega/_NY/auth/jwt/filter/JwtVerificationFilter.java
  src/main/java/com/mega/_NY/auth/repository/UserRepository.java
  src/main/java/com/mega/_NY/auth/service/UserInfoFilter.java
  src/main/java/com/mega/_NY/auth/service/UserService.java
Labels: 🐛Bug, 👻help wanted, ✨Feat, 👻Etc, 🥕 채현영🥕

#23 ✨Feat: Item Add
  src/main/java/com/mega/_NY/item/dto/ItemDTO.java
  src/main/java/com/mega/_NY/item/entity/Item.java
  src/test/java/com/mega/_NY/repository/AuthRepositoryTests.java
  src/test/java/com/mega/_NY/service/AuthServiceTests.java
Labels: ✨Feat, 🔮 이소현🔮

#24 🐛 Fix: Cart + Order Fix
  src/main/java/com/mega/_NY/auth/entity/User.java
  src/main/java/com/mega/_NY/cart/controller/CartController.java
  src/main/java/com/mega/_NY/cart/dto/CartDTO.java
  src/main/java/com/mega/_NY/cart/dto/ItemCartDTO.java
  src/main/java/com/mega/_NY/cart/entity/Cart.java
  src/main/java/com/mega/_NY/cart/service/CartService.java
  src/main/java/com/mega/_NY/cart/service/ItemCartService.java
  src/main/java/com/mega/_NY/orders/controller/OrdersController.java
  src/main/java/com/mega/_NY/orders/dto/ItemOrderDTO.java
  src/main/java/com/mega/_NY/orders/dto/OrdersDTO.java
  src/main/java/com/mega/_NY/orders/entity/ItemOrders.java
  src/main/java/com/mega/_NY/orders/entity/Orders.java
  src/main/java/com/mega/_NY/orders/service/ItemOrdersService.java
  src/test/java/com/mega/_NY/login/jwt/JwtTokenTest.java
  src/test/java/com/mega/_NY/repository/CartRepositoryTests.java
  src/test/java/com/mega/_NY/repository/OrderRepositoryTests.java
  src/test/java/com/mega/_NY/service/CartServiceTests.java
  src/test/java/com/mega/_NY/service/ItemCartServiceTests.java
Labels: 🐛Bug, 🧵Chore, 📌Test, 🦦 김신이🦦

#25 ✨ Feat: service 🐛Fix: tem test code 🧵Chore: entity, dto, repository
  src/main/java/com/mega/_NY/item/dto/ItemDTO.java
  src/main/java/com/mega/_NY/item/entity/Item.java
  src/main/java/com/mega/_NY/item/entity/ItemColor.java
  src/main/java/com/mega/_NY/item/mapper/ItemMapper.java
  src/main/java/com/mega/_NY/item/repository/ItemRepository.java
  src/main/java/com/mega/_NY/item/service/ItemService.java
  src/test/java/com/mega/_NY/controller/ItemControllerTest.java
  src/test/java/com/mega/_NY/controller/ItemControllerTests.java
Labels: 🐛Bug, ✨Feat, 📌Test, 🍸조민준🍸

#26 🐛Fix: Cart + Order Entity Fix
  src/main/java/com/mega/_NY/auth/entity/User.java
  src/main/java/com/mega/_NY/cart/entity/Cart.java
  src/main/java/com/mega/_NY/cart/repository/CartRepository.java
  src/main/java/com/mega/_NY/cart/service/CartService.java
  src/main/java/com/mega/_NY/orders/controller/OrdersController.java
  src/main/java/com/mega/_NY/orders/entity/Orders.java
  src/main/java/com/mega/_NY/orders/repository/OrdersRepository.java
  src/main/java/com/mega/_NY/orders/service/OrdersService.java
  src/test/java/com/mega/_NY/repository/CartRepositoryTests.java
  src/test/java/com/mega/_NY/repository/OrderRepositoryTests.java
  src/test/java/com/mega/_NY/service/CartServiceTests.java
Labels: 🐛Bug, 🧵Chore, 📌Test, 🦦 김신이🦦

#27 🐛Fix: Entity type, ✨Feat: Enum - size, color
  src/main/java/com/mega/_NY/item/dto/ItemDTO.java
  src/main/java/com/mega/_NY/item/entity/Item.java
  src/main/java/com/mega/_NY/item/entity/ItemSize.java
  src/test/java/com/mega/_NY/controller/ItemControllerTests.java
Labels: ♻️Refactor, ✨Feat, 📌Test, 🍸조민준🍸

#28 🐛 Fix: Cart + Order, Feat: OrderFromCart
  src/main/java/com/mega/_NY/auth/controller/UserController.java
  src/main/java/com/mega/_NY/cart/controller/CartController.java
  src/main/java/com/mega/_NY/cart/controller/ItemCartController.java
  src/main/java/com/mega/_NY/cart/service/CartService.java
  src/main/java/com/mega/_NY/cart/service/ItemCartService.java
  src/main/java/com/mega/_NY/orders/controller/OrdersController.java
  src/main/java/com/mega/_NY/orders/service/OrdersService.java
  src/test/java/com/mega/_NY/controller/CartControllerTests.java
  src/test/java/com/mega/_NY/controller/ItemCartControllerTests.java
Labels: 🐛Bug, ✨Feat, 📌Test, 🦦 김신이🦦

#29 ✨Feat: Category Add
  src/main/java/com/mega/_NY/category/controller/CategoryController.java
  src/main/java/com/mega/_NY/category/dto/CategoryDTO.java
  src/main/java/com/mega/_NY/category/entity/Category.java
  src/main/java/com/mega/_NY/category/repository/CategoryRepository.java
  src/main/java/com/mega/_NY/category/service/CategoryService.java
  src/main/java/com/mega/_NY/item/dto/ItemDTO.java
  src/main/java/com/mega/_NY/item/entity/Item.java
  src/main/java/com/mega/_NY/item/entity/ItemCategory.java
  src/main/java/com/mega/_NY/item/service/ItemService.java
  src/test/java/com/mega/_NY/controller/ItemControllerTests.java
Labels: ✨Feat, 👻Etc, 🔮 이소현🔮

#30 ✨Feat: Category function
  .idea/misc.xml
  src/main/java/com/mega/_NY/category/controller/CategoryController.java
  src/main/java/com/mega/_NY/category/dto/CategoryDTO.java
  src/main/java/com/mega/_NY/category/entity/Category.java
  src/main/java/com/mega/_NY/category/repository/CategoryRepository.java
  src/main/java/com/mega/_NY/category/service/CategoryService.java
  src/main/java/com/mega/_NY/item/controller/ItemController.java
  src/main/java/com/mega/_NY/item/entity/Item.java
  src/main/java/com/mega/_NY/item/repository/ItemRepository.java
  src/main/java/com/mega/_NY/item/service/ItemService.java
  src/test/java/com/mega/_NY/controller/ItemControllerTests.java
Labels: ✨Feat, 📌Test, 👻Etc, 🔮 이소현🔮

#31 🐛Fix: Order CRUD Fix (in progress...)
  .idea/misc.xml
  src/main/java/com/mega/_NY/auth/config/exception/ExceptionCode.java
  src/main/java/com/mega/_NY/orders/controller/OrdersController.java
  src/main/java/com/mega/_NY/orders/dto/ItemOrderDTO.java
  src/main/java/com/mega/_NY/orders/entity/ItemOrders.java
  src/main/java/com/mega/_NY/orders/entity/Orders.java
  src/main/java/com/mega/_NY/orders/mapper/ItemOrdersMapper.java
  src/main/java/com/mega/_NY/orders/service/OrdersService.java
Labels: 🐛Bug, 🧵Chore, 👻Etc, 🦦 김신이🦦

#32 ✨Feat: Feat ImageUpload
  src/main/java/com/mega/_NY/item/controller/ItemController.java
  src/main/java/com/mega/_NY/item/dto/ItemDTO.java
  src/main/java/com/mega/_NY/item/entity/Item.java
  src/main/java/com/mega/_NY/item/service/ItemService.java
  src/main/resources/static/images/1719563793390_kakao_login_medium_narrow.png
  src/main/resources/static/images/1719563793393_kakao_login_medium_narrow.png
  src/main/resources/static/images/1719565400094_Do-tori (2).png
  src/main/resources/static/images/1719565400097_Do-tori (2).png
Labels: ✨Feat, 🔮 이소현🔮

#33 ✨Feat: FileUpload Add
  src/main/java/com/mega/_NY/item/controller/ItemController.java
  src/main/java/com/mega/_NY/item/dto/ItemDTO.java
  src/main/java/com/mega/_NY/item/service/ItemService.java
  src/main/resources/static/images/1719563793390_kakao_login_medium_narrow.png
  src/main/resources/static/images/1719563793393_kakao_login_medium_narrow.png
  src/main/resources/static/images/1719565400094_Do-tori (2).png
  src/main/resources/static/images/1719565400097_Do-tori (2).png
  src/test/java/com/mega/_NY/controller/ItemControllerTests.java
Labels: ✨Feat, 👻Etc, 🔮 이소현🔮

#34 🐛Fix: Order CRUD Code Fix
  src/main/java/com/mega/_NY/cart/entity/Cart.java
  src/main/java/com/mega/_NY/cart/service/CartService.java
  src/main/java/com/mega/_NY/cart/service/ItemCartService.java
  src/main/java/com/mega/_NY/orders/controller/OrdersController.java
  src/main/java/com/mega/_NY/orders/dto/OrdersDTO.java
  src/main/java/com/mega/_NY/orders/entity/ItemOrders.java
  src/main/java/com/mega/_NY/orders/entity/Orders.java
  src/main/java/com/mega/_NY/orders/mapper/ItemOrdersMapper.java
  src/main/java/com/mega/_NY/orders/mapper/OrdersMapper.java
  src/main/java/com/mega/_NY/orders/service/OrdersService.java
Labels: 🐛Bug, 🧵Chore, 👻Etc, 🦦 김신이🦦

#35 ✨Feat: modify, delete, info finish
  src/main/java/com/mega/_NY/auth/config/SecurityConfig.java
  src/main/java/com/mega/_NY/auth/config/exception/ExceptionCode.java
  src/main/java/com/mega/_NY/auth/controller/UserController.java
  src/main/java/com/mega/_NY/auth/dto/UserDTO.java
  src/main/java/com/mega/_NY/auth/entity/User.java
  src/main/java/com/mega/_NY/auth/repository/UserRepository.java
  src/main/java/com/mega/_NY/auth/service/UserInfoFilter.java
  src/main/java/com/mega/_NY/auth/service/UserService.java
Labels: 🐛Bug, 👻help wanted, ✨Feat, 👻Etc, 🥕 채현영🥕

#37 🐛 Fix: CreateItem Fix
  .idea/misc.xml
  src/main/java/com/mega/_NY/item/controller/ItemController.java
Labels: 🐛Bug, 👻Etc, 🔮 이소현🔮
